application: guestbooklh
version: 4
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /api/(.*)
  script: api/wrapper.php
 
- url: /routes/
  static_dir: routes/
  application_readable: true
  
- url: /stops/
  static_dir: stops/
  application_readable: true

- url: /js/
  static_dir: js/
  
- url: /css
  static_dir: css
  
- url: /tool.html
  static_files: tool.html
  upload: tool.html
  
- url: /maptool.html
  static_files: maptool.html
  upload: maptool.html

- url: /
  script: index.php
#  static_files: index.html
#  upload: index.html

